### ISSUE TITLE
Doesn't count words with no-latin letters

### ISSUE THREAD

**Issue by dadyarri** [robole/vscode-marky-stats#1]
There is a bug:
If word not contains a latin letter it doesn't counts.
![image](https://user-images.githubusercontent.com/51821039/101789611-90387000-3b12-11eb-9f0f-a7df78b06bae.png)

**Comment by robole** [comment]
Thanks @dadyarri  for raising the issue.

I don't have time to look into at the moment. You're welcome to submit a PR if you are interested?

**Comment by dadyarri** [comment]
@robole, i don't know JS, so can't do anything with it

**Comment by dadyarri** [comment]
@robole, phew, checked word counter's code: it's easier, than i thought. I'll try to make pr.
Can I include third-party regexp engine to support Unicode, http://xregexp.com/ for example?

**Comment by robole** [comment]
@dadyarri What might be better is if you can find an extension that works with cryllic, did you find another extension already? 

For example, does [word count](https://marketplace.visualstudio.com/items?itemName=ms-vscode.wordcount) work?

Changing the regex to might be sufficient. I know there are some unicode related features available in most regexp engines. 

If you can find a working example, I can make the change.

**Comment by dadyarri** [comment]
@robole, as far as i understand (https://stackoverflow.com/questions/18471159/regular-expression-with-the-cyrillic-alphabet), default js's regexp engine works pretty bad with Unicode.
Sure, easiest way is to change regexp to something like `/[\wа-яё]+/ig`, but i think it's not so good, because of non-latin and non-cyrrilic languages i. e. Chinese or Czech.

In conclusion, I don't know how to implement this without dependencies

I'll try the extension, you've sent later, thanks.

**Comment by robole** [comment]
@dadyarri Thanks for your help. I pushed the change to the Visual Studio Marketplace now. The latest version will be v0.2.1.
