### ISSUE TITLE
Show word count of selection

### ISSUE THREAD

**Issue by euclip** [robole/vscode-marky-stats#10]
Despite the "Contributions" section of the README, this isn't a bug, but a feature request. It would be nice to be able to see the word count of just the current selection separately from that of the document as a whole. What this could maybe look like in the status bar is something like this: `Words: 500 (29 selected)`.

**Comment by robole** [comment]
hi @euclip ,

i wont be adding more features to this extension.

all the best

**Comment by eclecticpassions** [comment]
Is there any chance you might reconsider adding this feature, Rob?
