### ISSUE TITLE
Support for Latex files (.tex)

### ISSUE THREAD

**Issue by fjulian** [robole/vscode-marky-stats#11]
Nice extension, thanks for providing it!

It would be great if the stats could also be shown for .tex files, which commonly contain Latex text. Is it already or would it be possible to expose a setting for the file endings that trigger this extension to show the stats?

**Comment by robole** [comment]
hi @fjulian 

I am glad you like the extension. As I stated in the README, I consider this extension feature complete. I have other demands on my time.

If you would like to add support, you can fork the extension. You need to change the [activation events](https://code.visualstudio.com/api/references/activation-events)  in the `package.json`. You can add another language here:

```json
"activationEvents": [
    "onLanguage:markdown"
  ],
```

If you want to publish another version of the extension to the VS Code marketplace, it would be preferable if you use another name.

Kind Regards,

Rob
