### ISSUE TITLE
Error if try to run statistic display right after install; Restart required

### ISSUE THREAD

**Issue by dadyarri** [robole/vscode-marky-stats#2]
If open statistic display right after extension installing, without restart then VSCode will show an error "command `marky-stats.SelectItem` not found. After restarting it works.

*Possible solution*
May be need to make button "Reload required" and hide extension's option from `^ShiftP` menu until restart?

**Comment by robole** [comment]
There is a "reload required" button that covers this scenario, but it is inside the **Extensions** tab as below.

![reload-required](https://user-images.githubusercontent.com/3703647/102076736-2508d980-3e43-11eb-9817-07d41a230f5d.png)

There is no way for me  to show it in another way.
