### ISSUE TITLE
Statistic Choice Resets Upon Reopening Window

### ISSUE THREAD

**Issue by micharris42** [robole/vscode-marky-stats#4]
The default statistic shown in the Status Bar is "Reading Time". After opening the settings and changing to "Words", this is the statistic now shown in the Status Bar.

However, after closing and reopening the program, the statistic shown in the Status Bar is once again "Reading Time", despite the setting still being set to "Words".

I am using Marky Stats 0.4.1 with VSCodium 1.57.1. Please let me know if you need any further information. 

Thank you.

**Comment by robole** [comment]
hi @micharris42 ,

Thanks for reporting the error. There is an issue.

I fixed the issue and pushed an update out. Update to v0.4.2. and check to see its good on your end. If it is, you can close the issue.  👍

**Comment by micharris42** [comment]
@robole, thank you very much! Just tried out the new version with opening and closing windows, and as best I can tell the issue seems to be fixed.
