### ISSUE TITLE
Add option to show multiple stats at once.

### ISSUE THREAD

**Issue by ZenaMel** [robole/vscode-marky-stats#5]
For example I'm always interested in

`Words`

and

`Reading Time`

A config option (can be in JSON settings only too) that would allow us to choose which stat types to show in the status bar would be awesome.

**Comment by robole** [comment]
Hi,

Thank you for the suggestion.

I initially wrote this extension as an example project for teaching. So, im not sure if I want to add more to it! 

In any case, I dont have time to work on this atm. I will leave it open and if other people express an interest, I will consider it later.

**Comment by robole** [comment]
@Zenahr This feature has been implemented. You can thank @riuson for the bulk of the work.

You can show appreciation by starring the repo and leaving a review.
